# Generated by Django 3.1 on 2020-08-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='out_stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('interview', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_students', to='OutboundDiaries.branch')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_students', to='OutboundDiaries.university')),
            ],
        ),
    ]
