# Generated by Django 3.1 on 2020-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutboundDiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_stu',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
