# Generated by Django 3.1 on 2020-08-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OutboundDiaries', '0002_auto_20200826_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_stu',
            name='interview',
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='OutboundDiaries.out_stu')),
            ],
        ),
    ]
