# Generated by Django 3.1 on 2020-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutboundDiaries', '0003_auto_20200826_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_stu',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
